import { global } from "../common/attributes";
import { ElementSpec } from "../types";

export const input: ElementSpec = {
  contents: {
    model: null,
  },
  attributes: {
    global,
    specific: new Set([
      "accept",
      "alpha",
      "alt",
      "autocomplete",
      "checked",
      "colorspace",
      "dirname",
      "disabled",
      "form",
      "formaction",
      "formenctype",
      "formmethod",
      "formnovalidate",
      "formtarget",
      "height",
      "list",
      "max",
      "maxlength",
      "min",
      "minlength",
      "multiple",
      "name",
      "pattern",
      "placeholder",
      "popovertarget",
      "popovertargetaction",
      "readonly",
      "required",
      "size",
      "src",
      "step",
      "type",
      "value",
      "width",
      "title",
    ]),
  },
};
