import { IMPLICIT_ROLE } from "./accessibility/implicit-role";
import { Text, ValidURL } from "./attributes";
import { AnyAttribute } from "./attributes/any-attribute";
import { ElementSpec } from "./types";

const empty: [string, AnyAttribute][] = [];

export const elements: Record<string, ElementSpec> = {
  html: { globalAttributes: true, attributes: empty },
  head: { globalAttributes: true, attributes: empty },
  title: { globalAttributes: true, attributes: empty },
  base: {
    globalAttributes: true,
    attributes: [
      [
        "base",
        {
          type: ValidURL.type,
        },
      ],
      [
        "target",
        {
          // TODO
          type: Text.type,
        },
      ],
    ],
  },
  link: { globalAttributes: true },
  meta: { globalAttributes: true },
  style: { globalAttributes: true },
  body: { globalAttributes: true },
  article: { globalAttributes: true },
  section: { globalAttributes: true },
  nav: { globalAttributes: true },
  aside: { globalAttributes: true },
  hgroup: { globalAttributes: true },
  header: { globalAttributes: true },
  footer: { globalAttributes: true },
  address: { globalAttributes: true },
  p: { globalAttributes: true },
  hr: { globalAttributes: true },
  pre: { globalAttributes: true },
  blockquote: { globalAttributes: true },
  ol: { globalAttributes: true },
  ul: { globalAttributes: true },
  menu: { globalAttributes: true },
  li: { globalAttributes: true },
  dl: { globalAttributes: true },
  dt: { globalAttributes: true },
  dd: { globalAttributes: true },
  figure: { globalAttributes: true },
  figcaption: { globalAttributes: true },
  main: { globalAttributes: true },
  search: { globalAttributes: true },
  div: { globalAttributes: true },
  a: { globalAttributes: true },
  em: { globalAttributes: true },
  strong: { globalAttributes: true },
  small: { globalAttributes: true },
  s: { globalAttributes: true },
  cite: { globalAttributes: true },
  q: { globalAttributes: true },
  dfn: { globalAttributes: true },
  abbr: { globalAttributes: true },
  ruby: { globalAttributes: true },
  rt: { globalAttributes: true },
  rp: { globalAttributes: true },
  data: { globalAttributes: true },
  time: { globalAttributes: true },
  code: { globalAttributes: true },
  var: { globalAttributes: true },
  samp: { globalAttributes: true },
  kbd: { globalAttributes: true },
  i: { globalAttributes: true },
  b: { globalAttributes: true },
  u: { globalAttributes: true },
  mark: { globalAttributes: true },
  bdi: { globalAttributes: true },
  bdo: { globalAttributes: true },
  span: { globalAttributes: true },
  br: { globalAttributes: true },
  wbr: { globalAttributes: true },
  ins: { globalAttributes: true },
  del: { globalAttributes: true },
  picture: { globalAttributes: true },
  source: { globalAttributes: true },
  img: { globalAttributes: true },
  iframe: { globalAttributes: true },
  embed: { globalAttributes: true },
  object: { globalAttributes: true },
  video: { globalAttributes: true },
  audio: { globalAttributes: true },
  track: { globalAttributes: true },
  map: { globalAttributes: true },
  area: { globalAttributes: true },
  table: { globalAttributes: true },
  caption: { globalAttributes: true },
  colgroup: { globalAttributes: true },
  col: { globalAttributes: true },
  tbody: { globalAttributes: true },
  thead: { globalAttributes: true },
  tfoot: { globalAttributes: true },
  tr: { globalAttributes: true },
  td: { globalAttributes: true },
  th: { globalAttributes: true },
  form: { globalAttributes: true },
  label: { globalAttributes: true },
  input: { globalAttributes: true },
  button: { globalAttributes: true },
  select: { globalAttributes: true },
  datalist: { globalAttributes: true },
  optgroup: { globalAttributes: true },
  option: { globalAttributes: true },
  textarea: { globalAttributes: true },
  output: { globalAttributes: true },
  progress: { globalAttributes: true },
  meter: { globalAttributes: true },
  fieldset: { globalAttributes: true },
  legend: { globalAttributes: true },
  selectedcontent: { globalAttributes: true },
  details: { globalAttributes: true },
  summary: { globalAttributes: true },
  dialog: { globalAttributes: true },
  script: { globalAttributes: true },
  noscript: { globalAttributes: true },
  template: { globalAttributes: true },
  slot: { globalAttributes: true },
  canvas: { globalAttributes: true },
};
